name: auto
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update
        run: |
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/proxy.txt -nv -O ./list/proxy.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/gfw.txt -nv -O ./list/gfw.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/greatfire.txt -nv -O ./list/greatfire.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/tld-not-cn.txt -nv -O ./list/tld-not-cn.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/telegramcidr.txt -nv -O ./list/telegramcidr.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/apple.txt -nv -O ./list/apple.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt -nv -O ./list/cncidr.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/direct.txt -nv -O ./list/direct.list
          wget https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/auto-update/ruleset/ASN.China.list -nv -O ./list/ASN.China.list
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "action"
          name: update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'
jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update
        run: |
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/proxy.txt -nv -O ./list/proxy.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/gfw.txt -nv -O ./list/gfw.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/greatfire.txt -nv -O ./list/greatfire.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/tld-not-cn.txt -nv -O ./list/tld-not-cn.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/telegramcidr.txt -nv -O ./list/telegramcidr.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/apple.txt -nv -O ./list/apple.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt -nv -O ./list/cncidr.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/direct.txt -nv -O ./list/direct.list
          wget https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/auto-update/ruleset/ASN.China.list -nv -O ./list/ASN.China.list
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "action"
          git add .
          git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a
          git push
          git push
