name: auto copy

on:
  schedule:
    - cron: 05 13 * * *
  watch:
    types: [started]
  #push:
  #  branches:
  #    - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:
      - uses: actions/checkout@main

      - name: Run generate script
        run: |
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/proxy.txt -nv -O ./list/proxy.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/gfw.txt -nv -O ./list/gfw.list

      - name: Commit file
        run: |
          git config --global user.email rls3nrve@duck.com
          git config --global user.name chideap
          git add .
          git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a

      - name: Push changes
        uses: ad-m/github-push-action@main
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: ${{ github.repository }}
          retain_days: 1
