name: auto

on:
  schedule:
    - cron:  '30 7,19 * * *'
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'Invoke API unconditionally'
        type: boolean
        required: true
        default: true
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run generate script
        run: |
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/proxy.txt -nv -O ./list/proxy.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/gfw.txt -nv -O ./list/gfw.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/greatfire.txt -nv -O ./list/greatfire.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/tld-not-cn.txt -nv -O ./list/tld-not-cn.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/telegramcidr.txt -nv -O ./list/telegramcidr.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/apple.txt -nv -O ./list/apple.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/cncidr.txt -nv -O ./list/cncidr.list
          wget https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/direct.txt -nv -O ./list/direct.list
          wget https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/auto-update/ruleset/ASN.China.list -nv -O ./list/ASN.China.list

          git config --global user.email rls3nrve@duck.com
          git config --global user.name chideap
          git add .
          git commit -m "Update `date +%Y/%m/%d\ %H:%M:%S\ %Z`" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}

      - name: Cleanup Workflow Logs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          repository: ${{ github.repository }}
          retain_days: 1
